attr/attributes.go
attr/attributes_test.go

This makes the usage syntax prettier. Instead of `attr.Classes(map[string]bool{})`, we can just use `attr.Classes{}`.

Make attr.Classes a map type

---

attr/attributes.go
attr/attributes_test.go
gomponents.go
gomponents_test.go

When implemented, the `Place` method of the `Placer` interface tells `Render` in `El` where to put a Node. This is relevant for helpers that want to be rendered like attributes, inside the parent element.
Fixes the bug where `attr.Classes` was rendered outside the element.

Introduce Placer interface

---

gomponents.go

HTMLEscaper is not needed with strings.

Use HTMLEscapeString

---

gomponents.go
gomponents_test.go

This makes it easier to e.g. conditionally skip a component for rendering.

Don't render or error on nil children

---

Makefile
gomponents.go
gomponents_test.go

Just concatenating the strings is much faster.
Before:
```
make benchmark
go test -bench=.
goos: darwin
goarch: amd64
pkg: github.com/maragudk/gomponents
BenchmarkAttr/boolean_attributes-8         	 8194791	       139 ns/op
BenchmarkAttr/name-value_attributes-8      	 5143292	       229 ns/op
PASS
ok  	github.com/maragudk/gomponents	2.841s
```
After:
```
make benchmark
go test -bench=.
goos: darwin
goarch: amd64
pkg: github.com/maragudk/gomponents
BenchmarkAttr/boolean_attributes-8         	16755404	        67.0 ns/op
BenchmarkAttr/name-value_attributes-8      	10208625	       116 ns/op
PASS
ok  	github.com/maragudk/gomponents	2.702s
```

Remove fmt.Sprintf call in attribute Render

---

README.md
assert/assert.go
attr/attributes.go
el/elements.go
el/elements_test.go
examples/simple/simple.go
gomponents.go
gomponents_test.go

The Render function has been changed to take a `Writer` instead of returning a string. This makes it possible to generate documents without having the whole content in memory.

Render to Writer instead of string

---

README.md
attr/attributes_test.go
attr/boolean_test.go
attr/simple_test.go
components/documents_test.go
el/elements_test.go
el/simple_test.go
gomponents.go
gomponents_test.go

Previously, elements of kind void and empty elements generally would be rendered auto-closing (with a final `/` character in the start tag), which is allowed sometimes but arguably wrong. See https://dev.w3.org/html5/spec-LC/syntax.html#end-tags
This created problems with for example `textarea` and `script`, which cannot be auto-closing, or the browser renders it wrong.
Also clarified in the docs that this library outputs HTML5.
Fixes #42.

Render correct HTML5

---

attr/attributes.go
gomponents.go

It was a weird interface that tried to abstract away nodes being elements or attributes, but it doesn't really make sense. Now `Nodes` just have a `NodeType`.

Add NodeType which replaces the Placer interface

---

README.md
examples/dot-import/dot-import.go
examples/simple/simple.go
html/attributes.go
html/attributes_test.go
html/elements.go
html/elements_test.go

`a`, `form`, `img`, `input`, `label`, `option`, `progress`, `select`, and `textarea` are now just regular elements (without helper parameters), because:
- Sometimes the use case doesn't fit (`a` as anchor without href, for example)
- There's no reason these are special among the others, so streamlining them makes sense
Also added new attributes `action`, `alt`, `for`, `method` that I had somehow missed.

Simplify available elements

---

components/documents.go
components/elements.go
gomponents.go
html/elements.go
html/elements_test.go

This makes it clearer that the helpers return a `Node` of any kind, and that the type is not important.
This also streamlines the API, as attribute helpers already return just `Node`.

Return Node from all helpers instead of NodeFunc

---

components/documents.go
examples/simple/simple.go
html/elements.go
html/elements_test.go

There were a lot of elements previously, like `Em`, `H1`, and a lot more, that took a string as the first argument previously. This was weird when you wanted to mix elements to output html like `<strong><em>…</em></strong>` or `<h1>Something <em>something</em> something</h1>`. gomponents is not an HTML validator, so I want people to be able to use elements however they please, also without text content.
This also means that all elements now have the same API.

Streamline HTML element API

---

examples/tailwindcss/tailwindcss.go

The CSS style URLs from unpkg.com redirected to a different page, but the first request set a `Content-Type` header of `text/plain`. Using the direct URLs fixes this.
Fixes #75. Thanks to @gedw99 for reporting.

Fix TailwindCSS CDN URL in example

---

gomponents.go
gomponents_test.go

Because this can be a place of injection if untrusted data is passed, escape all attribute values.
This slows down rendering a bit, but we're still talking tiny increments compared to everything else.
```
$ make benchmark
go test -bench=.
goos: darwin
goarch: arm64
pkg: github.com/maragudk/gomponents
BenchmarkAttr/boolean_attributes-8         	13095948	        91.92 ns/op
BenchmarkAttr/name-value_attributes-8      	 9124303	       131.5 ns/op
BenchmarkEl/normal_elements-8              	 6384505	       187.4 ns/op
PASS
ok  	github.com/maragudk/gomponents	5.124s
```
```
$ make benchmark
go test -bench=.
goos: darwin
goarch: arm64
pkg: github.com/maragudk/gomponents
BenchmarkAttr/boolean_attributes-8         	11524586	        92.07 ns/op
BenchmarkAttr/name-value_attributes-8      	 7606478 …
```

Escape Attr values

---

components/elements.go
components/elements_test.go
html/attributes.go
html/attributes_test.go

These are often used in the `<head>` part of the HTML.

Add LinkStylesheet and LinkPreload components

---

.github/workflows/ci.yml
examples/simple/simple.go
examples/tailwindcss/tailwindcss.go
go.mod
gomponents.go
gomponents_generic.go
gomponents_generic_test.go
gomponents_non_generic.go
gomponents_non_generic_test.go
gomponents_test.go

Instead of waiting for a good time to switch the `Map` implementation, I've decided to just offer two implementations: one for Go versions before 1.18, and one for 1.18 and onwards. This is achieved using build tags in the source files.
This is obviously a breaking change for consumers of this library that use Go 1.18 and onwards.
See #88

Add generic Map implementation

---

codecov.yml

We don't need coverage for the example code and internal testing helpers.

Fix wrong codecov

---

html/attributes.go
html/attributes_test.go

`<time>`, `<del>` and `<ins>` can receive a [`datetime`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTimeElement/dateTime) attribute

Add datetime attribute

---

README.md
html/attributes.go
html/attributes_test.go
html/elements.go
html/elements_test.go

It can appear in a `<blockquote>`.
- Closes https://github.com/maragudk/gomponents/issues/189

Add `cite` attribute

---

html/attributes.go
html/elements.go

Just a small refactor to reuse a bit of logic

Reduce code duplication by reusing the correct function in deprecated functions

---

README.md
components/components.go
components/components_test.go
go.mod
gomponents_test.go
html/attributes.go
html/attributes_test.go
html/elements.go
html/elements_test.go
http/handler.go
http/handler_test.go
internal/assert/assert.go

This is a breaking change to move gomponents to my own import namespace.
I will obviously be careful with this, test it out in all kinds of scenarios, release betas, etc. But otherwise, because the `Node` interface is so simple and has basically never changed, I don't think this will break much. 🤞
Fixes #200

Move module to maragu.dev/gomponents namespace

---

README.md
internal/import/import_test.go

So we can be sure all dot imports work at the same time.

Add test for dot imports

---

components/components.go
components/components_test.go

This PR updates the HTML5 function to accept and render additional HTML attributes. An additional test case to validate this enhancement has been added as well.

Add support for additional HTML attributes in HTML5 template

---

components/components.go
gomponents.go

Hey! I just discovered this repo and I love being able to write templates while still having compile-time checks.
I was looking through the code and noticed slices aren't currently preallocated in `Map()` and `Classes.Render()`. Preallocating will improve performance since the resulting slice won't have to be grown dynamically during the append loop.

Improve performance of `Map` and `Classes.Render` by preallocating slices

---

README.md

Adding an example of the usage of the StyleEl tag given attribute and element name conflicts. 
I keep making this error and felt it might be ergonomically useful to put an example in the readme. This may also better enable LLMs to understand how to use the module.

Update README.md with example to clarify attribute and element name conflicts

---

html/elements.go
html/elements_test.go

Hey there,
Thanks for this project! Super cool idea and I've been exploring using it to replace the standard `html/template` package in one of my Go projects.
One thing I noticed, however, is that the [search element](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/search) appears to be missing. This PR adds it (and updates the tests, as well).
Please let me know if I've missed anything or if any changes should be made.
Thanks again!

Add "search" HTML element

---

LLMs.md
components/components.go
components/components_test.go
internal/assert/assert.go

This adds `components.JoinAttrs`, a helper to join attribute values with a given name. Example:
```go
func myButton(children ...g.Node) g.Node {
return Div(JoinAttrs("class", g.Group(children), Class("button")))
}
func myPrimaryButton(text string) g.Node {
return myButton(Class("primary"), g.Text(text))
}
func ExampleJoinAttrs() {
danceButton := myPrimaryButton("Dance")
_ = danceButton.Render(os.Stdout)
// Output: <div class="primary button">Dance</div>
}
```
Fixes #258

Add `components.JoinAttrs`
