maragudk/gomponents

assert/assert.go
gomponents.go
gomponents_test.go

Make NodeFunc and attr implement fmt.Stringer

---

el/elements.go
el/elements_test.go

Especially add elements that are either used in every document, that nearly always have text content, or that are almost always used with certain attributes.

Add a lot of common elements

---

el/elements.go
el/elements_test.go

This makes it possible to add attributes.

Add children varargs to h1-6, b, strong, i, em, img helpers

---

README.md
gomponents.go
gomponents_test.go

Like Text, but calls fmt.Sprintf before rendering.

Add Textf function

---

el/section.go
el/section_test.go

Add remaining sectioning elements as helpers

---

README.md
examples/simple/simple.go

* I removed the `fmt` module from the readme example so it will compile as-is.
* I was bothered with the raw `ul` look of the menu so I added minimal CSS to make it look more like a standard menu.

Some work on the examples

---

examples/simple/simple.go
gomponents.go
gomponents_test.go

`Map` makes it easier to build lists of elements without having to iterate.

Add Map function

---

README.md
assert/assert.go
components/documents.go

Also update readme with features.

Add package docs

---

components/elements.go
gomponents.go
gomponents_test.go

Used to inline conditional nodes.

Add If helper function

---

html/attributes.go
html/attributes_test.go

Add aria-* and role attributes

---

README.md
html/attributes.go
html/attributes_test.go
html/elements.go
html/elements_test.go

Add data- attribute helper

---

components/documents.go

Use g.If in HTML5 helper

---

README.md

Fix code in readme

---

svg/attributes.go
svg/attributes_test.go
svg/elements.go
svg/elements_test.go

Introducing SVG, to inline vector graphics in your HTML! 🥳

Add svg package and a few helpers

---

components/attributes_test.go
gomponents.go
gomponents_test.go

Add examples in test files

---

gomponents_test.go

Add javascript alert onclick handler to Raw example

---

html/attributes.go
html/attributes_test.go
html/elements.go
html/elements_test.go

Adds the `video` element and `loop`, `muted`, `playsinline`, `poster` attributes.

Add video element and related attributes

---

components/attributes_test.go
components/documents_test.go
components/elements_test.go
gomponents_test.go
html/attributes_test.go
html/elements_test.go
internal/assert/assert.go
svg/attributes_test.go
svg/elements_test.go

Using `t.Helper()`.
Also move the assert package to be internal.

Mark the assert test helpers as such

---

gomponents.go

Makes it easier to lookup by name.
Also, fixed some doc comments.

Make void elements a map

---

README.md

Also fix godoc badge to point to pkg.go.dev.

Add Go report card to readme

---

html/attributes.go
html/attributes_test.go

See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#step
Fixes #120.

Add Step attribute

---

html/attributes.go
html/attributes_test.go

Add "checked" bool attribute

---

.gitignore
html/attributes.go
html/attributes_test.go

Update attributes.go - add draggable attribute

---

.github/workflows/ci.yml

Test on Go 1.23 in CI

---

gomponents_test.go

It didn't actually work the way it was written.

Fix attr panic test

---

.github/workflows/ci.yml
README.md

Mainly the linter action is easier to use.

Upgrade CI workflow

---

.github/workflows/ci.yml
Makefile
html/elements_test.go

Benchmark large document and run in CI

---

html/attributes.go
html/attributes_test.go

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/th#scope

add Scope attribute helper

---

.github/workflows/ci.yml
.golangci.yml
README.md
gomponents.go

Upgrade to golangci/golangci-lint-action@v7

---

.github/workflows/claude.yml

Added steps to checkout dotfiles and prepend CLAUDE.md.

Enhance Claude with global CLAUDE.md
